### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by jscti** [MFlisar/ComposeDialogs#4]
Hi there.

First: your libs are awesome, bravo !

I'm trying to tune the behavior of the List Dialog and have a few remarks :

- DialogList.SelectionMode.SingleSelect : the whole line should be selectable (not only the radio button)
- DialogList.SelectionMode.SingleClickAndClose : 
  - there is no indication of the current value when dialog is open (and at the same time, it's not very explicit that the lines are clickable). Maybe the Radio button could be shown like in the DialogList.SelectionMode.SingleSelect mode ?
  - the "OK" button looks like a "submit" but not needed as it is a click&close behavior. Maybe it should be hidden in this case ? or replaced by a "cancel" button ?
- There is a "ok" button but maybe an optional "cancel" button could be usefull to let user explicitely cancel

Well, to sum it all up : I'm switching from legacy PreferenceScreen and I try not to disrupt legacy behavior well summarized by this example (gmail settings) :

![image](https://github.com/MFlisar/ComposeDialogs/assets/1594035/667b0388-35ec-449e-b0c7-cc8a70a08468)

- radio button to show current value + explicit "this line is clickable" info to the user
- auto dismiss on click
- no "submit/ok" button
- "cancel" button

Could this be added as a new SingleSelectAndClose maybe ?

Thanks

**Comment by MFlisar** [comment]
**1) Single Selection Mode**

> DialogList.SelectionMode.SingleSelect : the whole line should be selectable (not only the radio button)

Please check out `selectOnRadioButtonClickOnly` in following code:

https://github.com/MFlisar/ComposeDialogs/blob/da0e3af19403da3c68a810a42f0fc48cfae0394b/library/modules/list/src/main/java/com/michaelflisar/composedialogs/dialogs/list/DialogList.kt#L314-L324

**2) Single Click and Close Mode**

This mode is just a click mode without indicators.

**3) Buttons**

Buttons are common for all dialogs, there is no special behaviour for lists. So simply adjust them to your needs manually. Following is part of every dialog:

https://github.com/MFlisar/ComposeDialogs/blob/da0e3af19403da3c68a810a42f0fc48cfae0394b/library/modules/list/src/main/java/com/michaelflisar/composedialogs/dialogs/list/DialogList.kt#L76

Every dialog does support an ok and/or cancel button or even none, simply set it up yourself.

**Adjustments I'll make in the next update:**

I will add an `closeOnSelectionChanged` `boolean` to the `SingleSelect` class which will allow you to use the single select mode like the click and close mode. This in combination with all the information above should solve all your problems.

**Comment by jscti** [comment]
Thanks for your details and the new `closeOnSelectionChanged `  👍 

And it's already coded and released !
And tested, that's perfect.

**Comment by jscti** [comment]
@MFlisar 

Actually maybe the new `closeOnSelectionChanged   `should have been a `closeOnSelection` even if the selection did'nt change.
Because a user reopening just to check/confirm its selection will : 
- tap value to reconfirm it
- nothing happens
- must hit bottom "cancel" button or dismiss modal by clicking elsewhere

which is not optimal, a tap on a already selected value should just close the dialog like when he chooses another value.

**Comment by MFlisar** [comment]
that makes sense for this special mode, so I changed it
